name: trimtree-backend

services:
  backend:
    image: trimtree
    build: .
    ports:
      - "3030:3030"
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s