export const data = [
  {
    id: 1,
    userProfile: "/images/team/user.jpg",
    ratings: 4.8,
    body: "Absolutely love my new look! Velvera completely transformed my hair with the perfect cut and color, enhancing both its style and health. I've never felt more confident and refreshed!",
    name: "Emma Rose",
    service: "Balayage & Styling",
    rowSpan: "row-span-4",
  },
  {
    id: 2,
    userProfile: "/images/team/user.jpg",
    ratings: 4.9,
    body: "The keratin treatment at Velvera was life-changing! My hair is now so smooth and manageable. The team was professional and made me feel pampered throughout the entire session.",
    name: "Priya Sharma",
    service: "Keratin Treatment",
    rowSpan: "row-span-4",
  },
  {
    id: 3,
    userProfile: "/images/team/user.jpg",
    ratings: 4.7,
    body: "I've been coming to Velvera for months now and every visit exceeds my expectations. The hair spa is incredibly relaxing and my hair feels healthier than ever. Highly recommend!",
    name: "Sarah Johnson",
    service: "Hair Spa",
    rowSpan: "row-span-4",
  },
  {
    id: 4,
    userProfile: "/images/team/user.jpg",
    ratings: 4.6,
    body: "Best hair salon experience ever! The stylist really listened to what I wanted and delivered beyond my expectations. The ambiance is luxurious and the service is top-notch.",
    name: "Ananya Patel",
    service: "Hair Cut & Blow Dry",
    rowSpan: "row-span-4",
  },
  {
    id: 5,
    userProfile: "/images/team/user.jpg",
    ratings: 4.9,
    body: "The global hair color service is amazing! I was nervous about going blonde but the team at Velvera made it perfect. The L'Oréal products they use are premium quality.",
    name: "Jessica Miller",
    service: "Global Hair Colour",
    rowSpan: "row-span-4",
  },
  {
    id: 6,
    userProfile: "/images/team/user.jpg",
    ratings: 4.5,
    body: "I had my bridal makeup and hair done at Velvera and I looked absolutely stunning! They understood my vision perfectly and made my special day even more memorable.",
    name: "Riya Verma",
    service: "Bridal Hair & Makeup",
    rowSpan: "row-span-4",
  },
  {
    id: 7,
    userProfile: "/images/team/user.jpg",
    ratings: 4.8,
    body: "The attention to detail at Velvera is incredible. My highlights came out exactly as I imagined. The staff is friendly and the salon environment is so clean and welcoming.",
    name: "Olivia Brown",
    service: "Highlights & Toning",
    rowSpan: "row-span-4",
  },
  {
    id: 8,
    userProfile: "/images/team/user.jpg",
    ratings: 4.7,
    body: "Finally found a salon that understands curly hair! The cut and treatment I received have made my curls more defined and healthy. Thank you Velvera for the amazing transformation!",
    name: "Neha Kapoor",
    service: "Curly Hair Treatment",
    rowSpan: "row-span-4",
  },
  {
    id: 9,
    userProfile: "/images/team/user.jpg",
    ratings: 4.6,
    body: "I treated myself to a hair botox treatment and wow! My damaged hair is now silky smooth and shiny. The results are long-lasting and worth every penny. Velvera is the best!",
    name: "Sophia Davis",
    service: "Hair Botox Treatment",
    rowSpan: "row-span-4",
  },
];
